#!/usr/bin/python
import sys
import os
from getpass import getuser
def getAbsolutePath(path):
	if path == None:
		print "path is illegal"
		exit()
	fname = os.popen("basename "+path).read()
	dirname = os.popen("dirname "+path).read()
	os.chdir(dirname.strip())
	absolutepath = os.popen("pwd").read()
	return (absolutepath.strip()+"/"+fname).strip()
def getUser():
	user = getuser()
	return user
def getHostnames(fpath):
	if fpath == None:
		exit()
	hostnames = []
	with open(fpath,'r') as slaves:
		for line in slaves:
			hostnames.append(line.strip())
	return hostnames
if __name__ == '__main__':
	if len(sys.argv) != 2:
		print "illegal argments"
		exit()
	args = sys.argv[1]
	path = getAbsolutePath(args);
	itemdir = os.popen("dirname "+path).read()
	user = getUser()
	hostnames = getHostnames('/usr/local/hadoop/etc/hadoop/slaves')
	for hostname in hostnames:
		print "------------"+hostname+"--------------"
		print "rsync -rvl "+path+" "+user+"@"+hostname+":"+itemdir
		os.popen("rsync -rvl "+path+" "+user+"@"+hostname+":"+itemdir)
